### ISSUE TITLE
Generated paths use backslash "\" on Windows

### ISSUE THREAD

**Issue by svpace** [lexich/grunt-css-image#3]
Image paths are generated with "\" instead of "/" on Windows which is interpreted as escape and not as path separator.

**Comment by lexich** [comment]
Try to update

**Comment by svpace** [comment]
Updated. Still generating backslashes.

**Comment by maximkoretskiy** [comment]
@svpace can you show your output of `npm ls`?

**Comment by lexich** [comment]
@svpace @maximkoretskiy Update version
